version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.33.0
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - ENABLE_MODULES=text2vec-transformers
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/lib/weaviate
